In [2]:
from functions import *
import pandas as pd
import duckdb

### WTP Province

In [39]:
conn = duckdb.connect()
conn.execute("""
    INSTALL postgres;
    LOAD postgres;
             
    ATTACH 'dbname=nt user=postgres host=localhost port=5433' AS t (TYPE postgres, SCHEMA temp);
    ATTACH 'dbname=nt user=postgres host=localhost port=5433' AS s (TYPE postgres, SCHEMA staging);
""")

In [49]:
# Load tables
df_pr = pd.read_csv('../../files/pnt_wtpdp_province.csv') # Contains suitable species per province and elevation range
df_ge = pd.read_csv('../../files/pnt_wtpdp_general.csv') # Contains purpose for each species
df_nt = conn.execute("SELECT * FROM s.ntapi_species").fetchdf() # Working table

In [ ]:
df_pr.head(5)

,family,scientific_name,common_name,size,spec_gravity,lumber,plywood,wood_comp_board,pulp_paper
0,Anacardiaceae,Dracontomelon dao,Dao,L,0.57,True,True,False,False
1,Anacardiaceae,Dracontomelon edule,Lamio,L,0.44,True,True,False,False
2,Anacardiaceae,Koordersiodension pinnatum,Amugis,M,0.69,True,False,False,False
3,Anacardiaceae,Mangifera altissima,Pahutan,M,0.55,True,False,False,False
4,Anacardiaceae,Pistacia chinensis,Sangilo,S,0.67,True,False,False,False

In [42]:
df_ge.head(5)

,family,scientific_name,common_name,size,spec_gravity,lumber,plywood,wood_comp_board,pulp_paper
0,Anacardiaceae,Dracontomelon dao,Dao,L,0.57,True,True,False,False
1,Anacardiaceae,Dracontomelon edule,Lamio,L,0.44,True,True,False,False
2,Anacardiaceae,Koordersiodension pinnatum,Amugis,M,0.69,True,False,False,False
3,Anacardiaceae,Mangifera altissima,Pahutan,M,0.55,True,False,False,False
4,Anacardiaceae,Pistacia chinensis,Sangilo,S,0.67,True,False,False,False

In [45]:
df_nt.head(5)

,id,common_name,species,family,ecological_classification,conservation_status,binhi_priority
0,1,Malapasnit,Kibatalia longifolia Merr.,Apocynaceae,Endemic,Critically Endangered,None
1,2,None,Amorphophallus palawanensis Bogner & Hett.,Araceae,Endemic,Critically Endangered,None
2,3,None,"Amorphophallus natolii Hett., A.Wistuba, V.B.A...",Araceae,Endemic,Critically Endangered,None
3,4,Takobtob,Areca parens Becc.,Arecaceae,Endemic,Critically Endangered,None
4,5,Valit,Calamus batanensis (Becc.) Baja-Lapis,Arecaceae,Endemic,Critically Endangered,None

Clean elevation columns of province table

In [50]:
# Do initial cleaning
df_pr = df_pr.replace('TRUE', True)
df_pr = df_pr.replace('FALSE', False)
df_pr = df_pr.rename(columns={'R': 'region', '0- 400': '0-400', '>1200':'1200'})
df_pr.columns = [x.lower() for x in df_pr.columns]
df_pr.head(5)

  region      province climate        species  0-400  400-800  800-1200   1200
0      1  Ilocos Norte      B4            Afu   True    False     False  False
1      1  Ilocos Norte      B5  Arangga-babae   True    False     False  False
2      1  Ilocos Norte      B6      Bagalunga   True     True     False  False
3      1  Ilocos Norte      B7      Bitanghol   True     True      True   True
4      1  Ilocos Norte      B8        Danupra   True    False     False  False

In [51]:
# If value is true in the elevation columns, append the column name to a new column
cols = list(df_pr.columns)[4:8]
mask = df_pr[cols].isin([True, 'TRUE']) 

# For each row, group the columns with True into a list
df_pr['elev_range_temp'] = mask.where(mask).stack().reset_index().groupby('level_0')['level_1'].agg(list) 
df_pr.head(5)

,region,province,climate,species,0-400,400-800,800-1200,1200,elev_range_temp
0,1,Ilocos Norte,B4,Afu,True,False,False,False,[0-400]
1,1,Ilocos Norte,B5,Arangga-babae,True,False,False,False,[0-400]
2,1,Ilocos Norte,B6,Bagalunga,True,True,False,False,"[0-400, 400-800]"
3,1,Ilocos Norte,B7,Bitanghol,True,True,True,True,"[0-400, 400-800, 800-1200, 1200]"
4,1,Ilocos Norte,B8,Danupra,True,False,False,False,[0-400]

In [52]:
# In the new column, the the minimum and maximum elevation range only
df_pr['elevation_range'] = df_pr['elev_range_temp'].apply(parse_elev)
df_pr = df_pr.drop(columns=['0-400', '400-800', '800-1200', '1200', 'elev_range_temp'], axis=1)
df_pr.head(5)

  region      province climate        species elevation_range
0      1  Ilocos Norte      B4            Afu        [0, 400]
1      1  Ilocos Norte      B5  Arangga-babae        [0, 400]
2      1  Ilocos Norte      B6      Bagalunga        [0, 800]
3      1  Ilocos Norte      B7      Bitanghol            [0+]
4      1  Ilocos Norte      B8        Danupra        [0, 400]

Join tables

# SCRATCH!

In [ ]:
# Create tables for faster joining
conn.execute("""
    DROP TABLE IF EXISTS what_to_plant_province_cleaned;
             
    CREATE TABLE what_to_plant_province_cleaned AS
    SELECT * FROM df;
""")

In [ ]:
df.to_sql('what_to_plant_province_cleaned', engine, if_exists='replace', schema='temp')

### WTP General

In [1]:
df2 = pd.read_csv('../pnt_wtpdp_general.csv')
df2.head(5)
df2.to_sql('what_to_plant_general_cleaned', engine, if_exists='replace', schema='temp')

NameError: name 'pd' is not defined

### Join to table

In [320]:
conn = psycopg2.connect('postgresql://miguel:portico@localhost:5433/nt')
cur = conn.cursor()

query = "SELECT * FROM staging.ntapi_species"
columns = ['id', 'common_name', 'species', 'family', 'ecological_classification', 'conservation_status', 'binhi_priority']

cur.execute(query)
rows = cur.fetchall()
cur.close

df_nt = pd.DataFrame(rows, columns=columns)
df_nt.head(5)

df_pr = df
df_ge = df2

In [323]:
df_pr.head(5)

  region      province climate        species elevation_range
0      1  Ilocos Norte      B4            Afu        [0, 400]
1      1  Ilocos Norte      B5  Arangga-babae        [0, 400]
2      1  Ilocos Norte      B6      Bagalunga        [0, 800]
3      1  Ilocos Norte      B7      Bitanghol            [0+]
4      1  Ilocos Norte      B8        Danupra        [0, 400]

In [324]:
df_ge.head(5)

,family,scientific_name,common_name,size,spec_gravity,lumber,plywood,wood_comp_board,pulp_paper
0,Anacardiaceae,Dracontomelon dao,Dao,L,0.57,True,True,False,False
1,Anacardiaceae,Dracontomelon edule,Lamio,L,0.44,True,True,False,False
2,Anacardiaceae,Koordersiodension pinnatum,Amugis,M,0.69,True,False,False,False
3,Anacardiaceae,Mangifera altissima,Pahutan,M,0.55,True,False,False,False
4,Anacardiaceae,Pistacia chinensis,Sangilo,S,0.67,True,False,False,False

In [325]:
df_nt.head(5)

,id,common_name,species,family,ecological_classification,conservation_status,binhi_priority
0,1,Malapasnit,Kibatalia longifolia Merr.,Apocynaceae,Endemic,Critically Endangered,None
1,2,None,Amorphophallus palawanensis Bogner & Hett.,Araceae,Endemic,Critically Endangered,None
2,3,None,"Amorphophallus natolii Hett., A.Wistuba, V.B.A...",Araceae,Endemic,Critically Endangered,None
3,4,Takobtob,Areca parens Becc.,Arecaceae,Endemic,Critically Endangered,None
4,5,Valit,Calamus batanensis (Becc.) Baja-Lapis,Arecaceae,Endemic,Critically Endangered,None

df_nt.common_name = df_ge.common_name

df_nt.species = df_ge.scientific_name

df_nt.family = df_ge.family

df_nt.species = df_pr.species

In [333]:
print(f'df_nt: {df_nt.shape[0]}')
print(f'df_ge: {df_ge.shape[0]}')
print(f'df_pr: {df_pr.shape[0]}')

df_nt: 995
df_ge: 140
df_pr: 1396

In [335]:
df_join_nt_ge_common_name = pd.merge(df_nt, df_ge, on='common_name', suffixes=('_nt_', '_ge'))
print(f'Joined NT to GE via common_name: {df_join_nt_ge_common_name.shape[0]}')

df_join_nt_ge_common_name = pd.merge(df_nt, df_ge, on='common_name', suffixes=('_nt_', '_ge'))
print(f'Joined NT to GE via common_name: {df_join_nt_ge_common_name.shape[0]}')

Joined NT to GE: 45